version: 2.1

orbs: 
  node: circleci/node@4.7.0

references:
  default_container_config: &default_container_config
    executor:
      name: node/default
      tag: '16.13'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  ssh_cache_key: &ssh_cache_key gcomponents-rev{{ .Revision }}

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - $HOME/.npm

  only_version_tags: &only_version_tags
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - save_cache:
          key: *ssh_cache_key
          paths:
            - ~/.ssh
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run Chromatic visual testing
          command: npx chromatic --exit-zero-on-changes

  release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Generate build
          command: npm run build
      - run:
          name: Publish npm package
          command: npx npm-prepublish --verbose && npm publish --access public

workflows:
  version: 2
  build-and-release:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - release_npm:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

