version: 2.1

orbs:
  doppler-circleci: ft-circleci-orbs/doppler-circleci@1.5.3
  node: circleci/node@5.2.0

references:
  default_container_config: &default_container_config
    executor:
      name: node/default
      tag: 'lts-browsers'
    resource_class: 'large'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  ssh_cache_key: &ssh_cache_key gcomponents-rev{{ .Revision }}

  only_version_tags: &only_version_tags
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - save_cache:
          key: *ssh_cache_key
          paths:
            - ~/.ssh
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Install Playwright
          command: npx playwright install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run Chromatic visual testing
          command: npx chromatic --exit-zero-on-changes

  release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - doppler-circleci/install
      - doppler-circleci/load_secrets
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Generate build
          command: npm run build
      - run:
          name: Publish to NPM
          command: |
            if [[ $CIRCLE_TAG =~ canary ]]
            then
              npm publish --access public --tag canary
            else
              npm publish --access public --tag latest
            fi

workflows:
  version: 2
  build-and-release:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - release_npm:
          context:
            - djd-npm-publish
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
