version: 2
references:
  default_container_config: &default_container_config
    docker:
      - image: circleci/node:12

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  npm_cache_key: &npm_cache_key v1-dependency-npm-{{ checksum "package-lock.json" }}

  ssh_cache_key: &ssh_cache_key gcomponents-rev{{ .Revision }}

  restore_ssh: &restore_ssh
    restore_cache:
      keys:
        - *ssh_cache_key

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - v1-dependency-npm-

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - $HOME/.npm

  only_version_tags: &only_version_tags
    tags:
      only: /^v.*$/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - save_cache:
          key: *ssh_cache_key
          paths:
            - ~/.ssh
      - *restore_node_modules
      - run:
          name: Install dependencies
          command: npm ci
      - *cache_node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run Chromatic visual testing
          command: npx chromatic --exit-zero-on-changes

  release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish npm package
          command: npx npm-prepublish --verbose && npm publish --access public

  test_release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc

  release_ghpr:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: printf "registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${GHPR_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish npm package
          command: npx npm-prepublish --verbose && npm publish

workflows:
  version: 2
  build-and-release:
    jobs:
      - install
      - test:
          requires:
            - install
      - test_release_npm:
          requires:
            - install
            - test
