version: 2
references:
  default_container_config: &default_container_config
    docker:
      - image: node:8

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  npm_cache_key: &npm_cache_key v1-dependency-npm-{{ checksum "package-lock.json" }}

  ssh_cache_key: &ssh_cache_key gcomponents-rev{{ .Revision }}
  restore_ssh: &restore_ssh
    restore_cache:
      keys:
        - *cache_key_ssh

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - v1-dependency-npm-

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - $HOME/.npm

  only_version_tags: &only_version_tags
    tags:
      only: /^v.*$/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - save_cache:
          key: *cache_key_ssh
          paths:
            - ~/.ssh
      - run:
          name: Upgrade npm
          command: npm i -g npm
      - run:
          name: Bower install
          command: npx bower install --allow-root
      - *restore_node_modules
      - run:
          name: Install dependencies
          command: npm ci --unsafe-perm
      - *cache_node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: npm test

  build_docs:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - *restore_ssh
      - add_ssh_keys:
          fingerprints:
            - 7d:cb:6b:f3:a3:0a:6b:11:54:70:30:ca:d7:f7:a3:00
      - run:
          name: Build storybook
          command: npm run build:storybook
      - run:
          name: Publish to gh-pages
          command: npm run publish-storybook
  release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish npm package
          command: ./node_modules/.bin/npm-prepublish --verbose && npm publish --access public

workflows:
  version: 2
  build-and-release:
    jobs:
      - install:
          filters:
            <<: *only_version_tags
      - test:
          requires:
            - install
          filters:
            <<: *only_version_tags
      - build_docs:
          requires:
            - install
            - test
          filters:
            <<: *only_version_tags
            branches:
              only: master
      - release_npm:
          requires:
            - install
            - test
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/
